### ISSUE TITLE
 ERROR:root:依赖导入错误：No module named 'apscheduler'

### ISSUE THREAD

**Issue by Slippoed** [Redcker/scripts#16]
老哥，这种情况怎么处理...拉了一天的依赖也没能解决

**Comment by Redcker** [comment]
> 老哥，这种情况怎么处理...拉了一天的依赖也没能解决

检查环境，运行脚本环境是否和安装依赖的环境一致

**Comment by Slippoed** [comment]
> > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> 
> 检查环境，运行脚本环境和安装依赖的环境一致
依赖拉进去了，，但又显示介个...
Traceback (most recent call last):
  File "Redcker_scripts_jx_cfd_hb.py", line 113, in <module>
    with open('cfd_config.json', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cfd_config.json'

**Comment by Redcker** [comment]
> > > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> > 
> > 
> > 检查环境，运行脚本环境和安装依赖的环境一致
> > 依赖拉进去了，，但又显示介个...
> > Traceback (most recent call last):
> > File "Redcker_scripts_jx_cfd_hb.py", line 113, in 
> > with open('cfd_config.json', 'r', encoding='utf-8') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: 'cfd_config.json'

配置文件没拉？

**Comment by Slippoed** [comment]
> > > > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> > > 
> > > 
> > > 查看环境，运行脚本但环境和安装的环境一致，拉进去了，又多
> > > 了个... 
> > > Traceback（最近调用最后一次）：
> > > 文件“Redcker_scripts_jx_cfd_hb.py”，第113行，in 
> > > with open(' cfd_config . json', 'r', encoding='utf-8') as f: 
> > > FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cfd_config.json'
> 
> 配置文件没拉？

拉进去了，cookie也手动改了，还是报错

**Comment by Redcker** [comment]
> > > > > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> > > > 
> > > > 
> > > > 查看环境，运行脚本但环境和安装的环境一致，拉进去了，又多
> > > > 了个...
> > > > Traceback（最近调用最后一次）：
> > > > 文件“Redcker_scripts_jx_cfd_hb.py”，第113行，in
> > > > with open(' cfd_config . json', 'r', encoding='utf-8') as f:
> > > > FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cfd_config.json'
> > 
> > 
> > 配置文件没拉？
> 
> 拉进去了，cookie也手动改了，还是报错

检查是否在同一级目录

**Comment by Slippoed** [comment]
> > > > > > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> > > > > 
> > > > > 
> > > > > 查看环境，运行脚本但环境和安装的环境一致，拉进去了，又多
> > > > > 了个... 
> > > > > Traceback（最近调用最后一次）：
> > > > > “Redcker_scripts_jx_cfd_hb.py”，第113行，in 
> > > > > with open(' cfd_config . json', 'r', encoding='utf-8') as f: 
> > > > > FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cfd_config.json'
> > > 
> > > 
> > > 配置文件没拉？
> > 
> > 
> > 拉进去了，cookie也手动改了，还是报错
> 
> 检查是否在同级目录

真的是这样，被您说中了...谢谢老哥，俺一时马虎放在子文件里了恍恍惚惚

**Comment by Redcker** [comment]
> > > > > > > 老哥，这种情况处理……拉了一天的依赖怎么能解决
> > > > > > 
> > > > > > 
> > > > > > 查看环境，运行脚本但环境和安装的环境一致，拉进去了，又多
> > > > > > 了个...
> > > > > > Traceback（最近调用最后一次）：
> > > > > > “Redcker_scripts_jx_cfd_hb.py”，第113行，in
> > > > > > with open(' cfd_config . json', 'r', encoding='utf-8') as f:
> > > > > > FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cfd_config.json'
> > > > 
> > > > 
> > > > 配置文件没拉？
> > > 
> > > 
> > > 拉进去了，cookie也手动改了，还是报错
> > 
> > 
> > 检查是否在同级目录
> 
> 真的是这样，被您说中了...谢谢老哥，俺一时马虎放在子文件里了恍恍惚惚

哈哈没事

**Comment by Slippoed** [comment]
老哥，脚本运行没有报错了，但遇到新情况就是，日志里面只显示类似于”## 开始执行... 2022-03-19 09:52:58“然后没有其他讯息。
