### ISSUE TITLE
QL报错

### ISSUE THREAD

**Issue by Chicuang** [Redcker/scripts#9]
![2022-03-09_194846](https://user-images.githubusercontent.com/26812145/157436440-16af4b7f-5b72-4d93-868c-5433a167a6a3.png)

**Comment by Redcker** [comment]
cookie没问题的话应该是IP黑了，在本地跑下试试

**Comment by Chicuang** [comment]
> cookie没问题的话应该是IP黑了，在本地跑下试试
![2022-03-09_204850](https://user-images.githubusercontent.com/26812145/157444906-461e3cfd-0e00-4476-8982-a18631868280.png)
本地跑是这样的，换了IP

**Comment by Redcker** [comment]
拉取最新代码，你这个不是最新的

**Comment by Redcker** [comment]
> 拉取最新代码，你这个不是最新的



> > cookie没问题的话应该是IP黑了，在本地跑下试试
> > ![2022-03-09_204850](https://user-images.githubusercontent.com/26812145/157444906-461e3cfd-0e00-4476-8982-a18631868280.png)
> > 本地跑是这样的，换了IP

拉取最新代码，你这个不是最新的
